!Max GMSL contributions for each ice sheet:

real, parameter :: LISmaxesl = 53.4  !Laurentide Ice Sheet
real, parameter :: GISmaxesl = 2.43  !Greenland Ice Sheet
real, parameter :: EISmaxesl = 7.23  !Eurasian Ice Sheet
real, parameter :: WAISmaxesl = 9.15 !West Antarctic Ice Sheet
real, parameter :: WLmaxesl = 0.450  !Wilkes Land, East Antarctica

! multiplication factor for shaving off 1 meter of GMSL equivalent

real, parameter :: LIS_esl = 0.018713785150333  !Laurentide Ice Sheet
real, parameter :: GL_esl = 0.101686851875593   !Greenland Ice Sheet
real, parameter :: EIS_esl = 0.138260922454651  !Eurasian Ice Sheet
real, parameter :: WA_esl = 0.047981339466128   !West Antarctic Ice Sheet
real, parameter :: WL_esl = 0.434531407552271   !Wilkes Land, East Antarctica 

