!Max e.s.l. contributions for each ice sheet:
! prem.l75.umvm7.lmvm7 !(cauchy)

real, parameter :: NAISmaxesl = 53.436543808038050
real, parameter :: GISmaxesl = 2.435812255166550
real, parameter :: EISmaxesl = 7.232701635764025
real, parameter :: WAISmaxesl = 9.145869082765119
real, parameter :: EAISmaxesl = 0.450145422809975

! multiplication factor for shaving off 1 meter of esl (specific to earth model)

!PREM.l75.umvm7.lmvm7 background maxwell

real, parameter :: NAm_esl = 0.018713785150333
real, parameter :: GL_esl = 0.101686851875593
real, parameter :: EIS_esl = 0.138260922454651
real, parameter :: WA_esl = 0.047981339466128
real, parameter :: EA_esl = 0.434531407552271

